### PR TITLE
fix(tailwind): Performance and stability

### LINKED ISSUE #549: SyntaxError: Invalid regular expression: invalid group specifier name
Im using react-email in a Remix project and just rendering the emails in the route directory:

```tsx
// routes/emails/reset-password.tsx
import { Tailwind } from "@react-email/tailwind"


export default function Template(props: { link?: string }) {
  return (
    <Tailwind>
      <h1 className="text-6xl">Reset Password</h1>
      <p>Click below to reset your password</p>
      <a href={props.link}>Reset Password</a>
    </Tailwind>
  )
}

```
When using the Tailwind component I get a `SyntaxError: Invalid regular expression: invalid group specifier name` in the console.

### LINKED ISSUE #999: Darkmode does not work with tailwind component
### Describe the Bug

When using the tailwind component the darkmode works after sending the email but not in preview
I have tried to make my device dark also forcefully setting the color-scheme to dark using chrome's rendering settings

image

The `dark:class` does not work in preview 

I have also added the head 
```jsx
<Head>
      <meta name="color-scheme" content="light dark" />
      <meta name="supported-color-schemes" content="light dark" />
 </Head>
````

### Which package is affected (leave empty if unsure)

@react-email/tailwind

### Link to the code that reproduces this issue

None

### To Reproduce

Just get create a text component and give it className 

```jsx
<Text className="text-white dark:text-black">Something</Text>
```

### Expected Behavior

The text should be dark on dark mode enabled or device dark mode

### What's your node version? (if relevant)

18.17.1

### LINKED ISSUE #1016: Huge performance degradation introduced with @react-email/components 0.0.8 and higher 🐢
### Describe the Bug

Context: I'm developing an AWS Lambda with SES and react-email, so execution time is critical. After upgrading @react-email/components to 0.0.8 or higher, the average execution time has increased tenfold.

To emulate an environment with limited resources, I ran my lambda in a Docker container with memory and CPU settings configured in docker-compose.yml.

Findings:
- The issue seems related to how @react-email/components handles Tailwind styles.
- The more Tailwind styles you incorporate, the more noticeable the performance degradation.

Below are some performance measurements. ([code base can be found here](https://github.com/nikita-resh/react-email-performance-issue)):

0.0.7

0.0.7 + tailwind (+31 % to execution time which is totally fine)
0 0 7 + tailwind

0.0.11

0.0.11 + tailwind (+11k % to execution time 🐢)
0 0 11 + tailwind

### Which package is affected (leave empty if unsure)

@react-email/components

### Link to the code that reproduces this issue

https://github.com/nikita-resh/react-email-performance-issue

### To Reproduce

Pre-requirements: 
- docker installed

I've prepared a public [GitHub repo](https://github.com/nikita-resh/react-email-performance-issue) with everything needed to reproduce the issue. You can find four commits in the main branch corresponding to each state from the attached images.

Here's how you can measure execution time on your own:

1. Checkout commit with
2. Execute `docker-compose build --no-cache` in root folder
3. Execute `docker-compose up` in root folder
4. Find `performance-issue-container  | EXECUTION: <x>s` in logs

Note: don't forget to add `--no-cache` flag after checkout a different commit

### Expected Behavior

Expect that the execution time will not increase after upgrading to @react-email/components 0.0.8 or higher.

### What's your node version? (if relevant)

18.17.1

### LINKED ISSUE #1021: Tailwind not parse the whole template component
### Describe the Bug

Before version 0.0.8, the following code is working normally
```tsc
<Tailwind>
  <Template />
</Tailwind>
```

After version 0.0.8, I found that it only analyzes Component with the Children attribute
```tsc
// it work fine
<Tailwind>
   <Component className="text-[100px]">React Email</Component>
</Tailwind>

// it not work for <div>
<Tailwind>
   <Component className="text-[100px]">
        <div className="text-red">Color</div>
        React Email
   </Component>
</Tailwind>
```

### Which package is affected (leave empty if unsure)

@react-email/tailwind

### Link to the code that reproduces this issue

[example in codesandbox](https://codesandbox.io/p/sandbox/vibrant-margulis-crq8hm?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clonm98zy000a3b6i81afg7gi%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clonm98zy00033b6iapcuchic%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clonm98zy00073b6ibopextq6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clonm98zy00093b6igdyq5oyu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clonm98zy00033b6iapcuchic%2522%253A%257B%2522id%2522%253A%2522clonm98zy00033b6iapcuchic%2522%252C%2522activeTabId%2522%253A%2522clonmbkc700np3b6ijcp8wzb3%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmain.tsx%2522%252C%2522id%2522%253A%2522clonma8no00ci3b6iov0q59i8%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522id%2522%253A%2522clonmabcu00g83b6inveu59ij%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FEmailTemplate%252Findex.tsx%2522%252C%2522id%2522%253A%2522clonmbkc700np3b6ijcp8wzb3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FEmailTemplate%252FRoot.tsx%2522%252C%2522id%2522%253A%2522clonmgh5j03by3b6iddxf0kkf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FEmailTemplate%252FBrand.tsx%2522%252C%2522id%2522%253A%2522clonmnp4805y23b6isn9t9qa4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clonm98zy00093b6igdyq5oyu%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clonm98zy00083b6i1866vpy0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clonm98zy00093b6igdyq5oyu%2522%252C%2522activeTabId%2522%253A%2522clonm98zy00083b6i1866vpy0%2522%257D%252C%2522clonm98zy00073b6ibopextq6%2522%253A%257B%2522id%2522%253A%2522clonm98zy00073b6ibopextq6%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clonm98zy00043b6iidsmudz1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clonm98zy00053b6ibl66efcf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%257D%252C%257B%2522id%2522%253A%2522clonm98zy00063b6i8d3w1k1f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522preview%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clonm98zy00043b6iidsmudz1%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### To Reproduce

I compared the latest version and the source code of version 0.0.8, and found that the 0.0.8 version was replaced by the entire HTML, while the latest version only analyzes Children after the version 0.0.8.

0.0.8
image

0.0.8+
image

### Expected Behavior

it can be parse the whole template component

### What's your node version? (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by gabrielmfern**
|        |   average `ms` per render   |
|--------|----------------------------:|
| before |         ~3197.14ms          |
| after  |           ~27.65ms          |

## What does this PR change?

This PR should implement performance changes and a rewrite with a few fixes.
Along with that I have also took the freedom to create a new `benchmarks`
folder in the monorepo that runs a real-world email's render process
with and without tailwind to compare the speed.

This PR solves the unbearably long time you needed to wait editing an email
due to the slowness from the `Tailwind` component. It also removes the dependency
on `tw-to-css` because it was not flexible enough to do the approach choosen.

A few issues that I tried solving with this to have the most stability possible
for the component were:
- Issues when trying to render emails on the browser due to look behind regular expressions (Closes #549)
- Issues with media queries not taking preference over styles and them not being applied at all (Closes #999)
- Performance issues that made it take seconds for just one render of a email that had the component (Closes #1016)
- Custom components not being processed at all by the Tailwind comoponent (Closes #1021)

## How does it fix the problems?

Going in a per-problem basis the fixes were:

- #549: Adding an eslint rule that disallows for lookbehind expressions on regexes
- #999: Forcing !important into media query tailwind generated selectors and keeping their classNames
- #1021: Rendering the component and then processing the resulting element (also made a patch as a workaround for people having the problem)
- #1016: Many small details overall of improvements, but mostly rendering the children to markup, computing the classes and then mapping the styles to each element's inline styles
    * This also included removing `tw-to-css` as a dependency

### CODE REVIEW

**Comment by eminx** [comment]
Great job!

**Comment by bukinoshita** [comment]
```diff
- feat(tailwind): performance and stability improvements
+ fix(tailwind): Performance an stability
```

File: benchmarks/tailwind-component/src/benchmark-current-vs-latest.ts [hunk 1]
```diff
@@ -0,0 +1,30 @@
+import { render } from "@react-email/render";
+import { Bench } from "tinybench";
+
+import EmailWithTailwind from "./emails/with-tailwind.js";
+
+import { Tailwind as CurrentTailwind } from "../../../packages/tailwind/dist";
+
+import { Tailwind as LatestTailwind } from "@react-email/tailwind";
```
Comment (bukinoshita) [inline benchmarks/tailwind-component/src/benchmark-current-vs-latest.ts:8]:
```suggestion
import { render } from "@react-email/render";
import { Bench } from "tinybench";
import EmailWithTailwind from "./emails/with-tailwind.js";
import { Tailwind as CurrentTailwind } from "../../../packages/tailwind/dist";
import { Tailwind as LatestTailwind } from "@react-email/tailwind";
```

File: benchmarks/tailwind-component/src/benchmark-current-vs-latest.ts [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+
+async function main() {
```
Comment (bukinoshita) [inline benchmarks/tailwind-component/src/benchmark-current-vs-latest.ts:10]: Can you convert to arrow function?

File: benchmarks/tailwind-component/src/emails/with-tailwind.tsx [hunk 3]
```diff
@@ -0,0 +1,199 @@
...
+  Html,
+  Img,
+  Link,
+  Preview,
+  Row,
+  Section,
+  Text,
+} from "@react-email/components";
+
+import type { TailwindProps } from "../../../../packages/tailwind/dist";
```
Comment (bukinoshita) [inline benchmarks/tailwind-component/src/emails/with-tailwind.tsx:16]:
```suggestion
} from "@react-email/components";
import type { TailwindProps } from "../../../../packages/tailwind/dist";
```

File: packages/tailwind/package.json [hunk 4]
```diff
@@ -44,21 +44,25 @@
     "node": ">=18.0.0"
   },
   "dependencies": {
+    "postcss": "8.4.31",
+    "postcss-css-variables": "^0.19.0",
```
Comment (bukinoshita) [inline packages/tailwind/package.json:48]: Pin the version

File: packages/tailwind/src/utils/get-css-for-markup.ts [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+  // eslint-disable-next-line no-var
+  var __OXIDE__: undefined;
+}
+
+global.__OXIDE__ = undefined;
+// to avoid __OXIDE__ undefined errors
+// this may cause problems later down the line when upadting tailwind
+// since tailwind might migrate to using oxide for their transformations
+
+export function getCSSForMarkup(
```
Comment (bukinoshita) [inline packages/tailwind/src/utils/get-css-for-markup.ts:17]: can you use arrow function and change the casing?

```suggestion
export function getCssForMarkup(
```

File: packages/tailwind/src/utils/get-css-for-markup.spec.tsx [hunk 6]
```diff
@@ -0,0 +1,22 @@
+import { renderToStaticMarkup } from "react-dom/server";
+import { getCSSForMarkup } from "./get-css-for-markup";
+import { minifyCSS } from "./minify-css";
+
+// these tests will fail if the minifyCSS is broken as well
+// the reason we use it here is because it just makes it simpler to compare
+// generated styles with expected ones
+describe("getCSSForMarkup()", () => {
```
Comment (bukinoshita) [inline packages/tailwind/src/utils/get-css-for-markup.spec.tsx:8]:
```suggestion
describe("getCssForMarkup()", () => {
```

**Comment by gabrielmfern** [comment]
We just released as a new canary everyone 🎉 !

You guys can now install `@react-email/tailwind@0.0.13-canary.1` and things should work

**Comment by Xexr** [comment]
Whilst this is dramatically faster, it appears to have broken the formatting on gmail for me.

Reverting to the previous version and its back to normal.

**Comment by gabrielmfern** [comment]
> Whilst this is dramatically faster, it appears to have broken the formatting on gmail for me.
> 
> Reverting to the previous version and its back to normal.

Interesting, can you maybe elaborate more on that so we can have it fixed? Also, any other problems you had with it?

We will get things fixed as soon as we can to move these changes into stable.

**Comment by gabrielmfern** [comment]
> Sure, happy to.
> 
> Here's an email I'm currently working on, and what it looks like the react-email preview and in most email clients:
> 
> image
> 
> Here's what it looks like in gmail:
> 
> image
> 
> It almost seems to go back to straight HTML, though clearly it's not quite that as there is the image still.
> 
> The same effect also happens on older emails that I know to be working, and are now exhibiting the same behaviour in gmail on the latest tailwind component version.
> 
> I've not noticed any other problems so far, but will let you know if I do.
> 
> Here's the relevant code (WIP, excuse my mess):
> 
> ```ts
> import {
>   Html,
>   Body,
>   Preview,
>   Container,
>   Heading,
>   Text,
>   Img,
>   Button,
>   Hr,
>   Link,
>   Font,
>   Head,
>   Section,
>   Row,
>   Column,
>   Tailwind,
> } from '@react-email/components';
> import * as React from 'react';
> import * as tw from '../tailwind.config';
> import { type WeeklySummary } from '@/db/getData';
> import { cn } from '../src/utils/utils';
> import { formatDistance } from 'date-fns';
> 
> export const WeeklySummaryEmail = (weeklyData: WeeklySummary) => {
>   return (
>     <Tailwind config={tw}>
>       <Html>
>         <Head>
>           <Font
>             fontFamily="Inter"
>             fallbackFontFamily="Verdana"
>             webFont={{
>               url: 'https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hiA.woff2',
>               format: 'woff2',
>             }}
>             fontWeight={400}
>             fontStyle="normal"
>           />
>         </Head>
>         <Preview>Keeping you on track</Preview>
>         <Body className="bg-black">
>           <Container className="bg-black text-gray-200">
>             <Container className="py-5">
>                                src={`https://dypt.app/logo_small.png`}
>                 width="144"
>                 height="40"
>                 alt="dypt"
>                 className="my-5 h-[40px] w-[144px]"
>               />
>               <Heading as="h2" className="pb-3 text-lg text-gray-200">
>                 Hello {weeklyData.username}
>               </Heading>
>               <Text className="text-gray-200">
>                 Here&apos;s a break down of your unarchived tasks:
>               </Text>
>               <Section className="m-0 w-[428px]">
>                 <Row>
>                   <Column>
>                     <NumberBox
>                       number={weeklyData.totalTasks || 0}
>                       label="Tasks"
>                       bgColor="bg-blue-700"
>                       labelColor="text-blue-400"
>                     />
>                   </Column>
> 
>                   <Column>
>                     <NumberBox
>                       number={weeklyData.totalTasksCompleted || 0}
>                       label="Completed"
>                       bgColor="bg-green-700"
>                       labelColor="text-green-400"
>                     />
>                   </Column>
> 
>                   <Column>
>                     <NumberBox
>                       number={weeklyData.totalTasksOutstanding || 0}
>                       label="Remaining"
>                       bgColor="bg-orange-700"
>                       labelColor="text-orange-400"
>                     />
>                   </Column>
> 
>                   <Column>
>                     <NumberBox
>                       number={weeklyData.totalTasksOverdue || 0}
>                       label="Overdue"
>                       bgColor="bg-red-700"
>                       labelColor="text-red-400"
>                     />
>                   </Column>
> 
>                   <Column>
>                     <NumberBox
>                       number={weeklyData.totalTasksDueThisWeek || 0}
>                       label="This week"
>                       bgColor="bg-yellow-700"
>                       labelColor="text-yellow-400"
>                     />
>                   </Column>
>                 </Row>
>               </Section>
>               <Text className="mt-5 text-gray-200">
>                 Your remaining tasks have these priorities assigned:
>               </Text>
>               <Section className="m-0 w-[343px]">
>                 <Row>
>                   <Column>
>                     <NumberBox
>                       number={
>                         weeklyData.totalTasksOutstanding -
>                           weeklyData.lowPriorityTasks -
>                           weeklyData.midPriorityTasks -
>                           weeklyData.highPriorityTasks || 0
>                       }
>                       label="None"
>                       bgColor="bg-slate-700"
>                       labelColor="text-slate-400"
>                     />
>                   </Column>
> 
>                   <Column>
>                     <NumberBox
>                       number={weeklyData.lowPriorityTasks || 0}
>                       label="Low"
>                       bgColor="bg-green-700"
>                       labelColor="text-green-400"
>                     />
>                   </Column>
> 
>                   <Column>
>                     <NumberBox
>                       number={weeklyData.midPriorityTasks || 0}
>                       label="Mid"
>                       bgColor="bg-orange-700"
>                       labelColor="text-orange-400"
>                     />
>                   </Column>
> 
>                   <Column>
>                     <NumberBox
>                       number={weeklyData.highPriorityTasks || 0}
>                       label="High"
>                       bgColor="bg-red-700"
>                       labelColor="text-red-400"
>                     />
>                   </Column>
>                 </Row>
>               </Section>
> 
>               {(weeklyData?.tasksOverdue?.length > 0 && (
>                 <>
>                   <Text className="mt-5 text-gray-200">
>                     You have {weeklyData.tasksOverdue.length} overdue tasks:
>                   </Text>
> 
>                   {weeklyData.tasksOverdue.map((task) => {
>                     return (
>                       <Task
>                         id={task.id}
>                         key={task.id}
>                         title={task.title}
>                         deadline={task.deadline}
>                       />
>                     );
>                   })}
>                 </>
>               )) || (
>                 <Text className="mt-5 text-gray-200">
>                   You have no overdue tasks.
>                 </Text>
>               )}
> 
>               {(weeklyData?.tasksDueThisWeek?.length > 0 && (
>                 <>
>                   <Text className="mt-5 text-gray-200">
>                     You have {weeklyData.tasksDueThisWeek.length} tasks due this
>                     week:
>                   </Text>
> 
>                   {weeklyData.tasksDueThisWeek.map((task) => {
>                     return (
>                       <Task
>                         id={task.id}
>                         key={task.id}
>                         title={task.title}
>                         deadline={task.deadline}
>                       />
>                     );
>                   })}
>                 </>
>               )) || (
>                 <Text className="mt-5 text-gray-200">
>                   You have no tasks due this week.
>                 </Text>
>               )}
> 
>               <Section className="m-0 w-[428px]">
>                 <Text className="mt-10 italic text-gray-300">
>                   Click on one of the info boxes or a task to see the detail on
>                   dypt.
>                 </Text>
> 
>                 <Text className="mt-3 italic text-gray-300">
>                   This is a weekly update email, sent every Monday morning
>                   summarising your tasks. Want to unsubscribe? You can disable
>                   it in your{' '}
>                   <Link
>                     href="https://dypt.app/user"
>                     className="px-0 text-sm text-blue-500"
>                   >
>                     dypt account settings
>                   </Link>{' '}
>                   at any time.
>                 </Text>
> 
>                 <Text className="mt-5 text-gray-200">
>                   Questions? Find us on twitter{' '}
>                   <Link
>                     href="https://twitter.com/dyptapp"
>                     className="px-0 text-sm text-blue-500"
>                   >
>                     @dyptapp
>                   </Link>{' '}
>                   or simply reply to this email.
>                 </Text>
>                 <Text className="m-0 p-0 text-gray-200">Best wishes, </Text>
>                 <Text className="m-0 p-0 text-gray-200">Dane</Text>
>                 <Button
>                   href="https://dypt.app/tasks"
>                   className="my-8 rounded-md bg-blue-600 px-3 py-2 text-sm "
>                   style={{ color: 'rgb(229 229 229)', padding: '10px 20px' }}
>                 >
>                   Go to your tasks
>                 </Button>
>               </Section>
> 
>               <Hr className="border border-blue-700" />
>               <Link href="https://dypt.app" className="text-sm text-gray-400">
>                 dypt.app
>               </Link>
>               <Text className="text-xs text-gray-400">
>                 beautiful tasks, infinitely divisible
>               </Text>
>             </Container>
>           </Container>
>         </Body>
>       </Html>
>     </Tailwind>
>   );
> };
> 
> export default WeeklySummaryEmail;
> 
> interface NumberBoxProps {
>   number: number;
>   label: string;
>   bgColor: string;
>   labelColor: string;
> }
> 
> const NumberBox = ({ number, label, bgColor, labelColor }: NumberBoxProps) => {
>   return (
>     <Section className={cn('h-20 w-20 rounded-md', bgColor)}>
>       <Row className="mt-[-12px]">
>         <Column
>           className={cn('pl-2 text-xs font-bold tracking-wider', labelColor)}
>           align="left"
>         >
>           {label}
>         </Column>
>       </Row>
>       <Row className="">
>         <Column className={cn('text-3xl text-gray-200')} align="center">
>           {number}
>         </Column>
>       </Row>
>     </Section>
>   );
> };
> 
> interface TaskProps {
>   id: number;
>   title: string;
>   deadline: Date | null;
> }
> 
> const Task = ({ id, title, deadline }: TaskProps) => {
>   // create a string using date-fns to display time until deadline
>   // if deadline is null, display nothing
>   const deadlineString = deadline
>     ? formatDistance(deadline, new Date(), { addSuffix: true })
>     : 'no deadline';
> 
>   return (
>     <Link href={`https://dypt.app/tasks/${id}`}>
>       <Section
>         className={cn(
>           'm-0 mb-3 w-[428px] rounded-md bg-slate-600 py-2.5 text-sm outline outline-1 outline-blue-900'
>         )}
>       >
>         <Row className="">
>           <Column
>             className={cn('pl-2 font-medium', 'text-gray-200')}
>             align="left"
>           >
>             {title}
>           </Column>
>           <Column
>             className={cn('pr-2 text-xs italic text-gray-200')}
>             align="right"
>           >
>             {deadlineString}
>           </Column>
>         </Row>
>       </Section>
>     </Link>
>   );
> };
> `
> ```

Just fixed the issues you had with that email. Can you please test out `@react-email/tailwind@0.0.13-canary.2`?

**Comment by Xexr** [comment]
Thanks for the quick response Gabriel,

Unfortunately, it's still the same for me. I've installed @react-email/tailwind@0.0.13-canary.2 and switched over the Tailwind component to import from that rather than the components package.

I still get the same broken formatting.

**Comment by gabrielmfern** [comment]
> Thanks for the quick response Gabriel,
> 
> Unfortunately, it's still the same for me. I've installed @react-email/tailwind@0.0.13-canary.2 and switched over the Tailwind component to import from that rather than the components package.
> 
> I still get the same broken formatting.

Now it just happens to be a different problem, some emails clients seem to just not support the syntax that tailwind uses for rgb so we needed to replace that, older versions already had it and I wasn't aware. Can you try out `@react-email/tailwind@0.0.13-canary.3` now?

**Comment by Xexr** [comment]
Thanks Gabriel,

That has largely fixed it for me.

One remaining bug I noticed: the button prop doesn't seem to apply text colour applied through tailwind, I'm having to manually overwrite through a style tag. Makes me wonder if it's a similar RGB related issue?

**Comment by gabrielmfern** [comment]
> Thanks Gabriel,
> 
> That has largely fixed it for me.
> 
> One remaining bug I noticed: the button component doesn't seem to apply text colour applied through tailwind, I'm having to manually overwrite through a style tag. Makes me wonder if it's a similar RGB related issue?

On what email client are you testing? Also what color are you using?

**Comment by Xexr** [comment]
It seems to happen on all email clients (including the react-email preview) and across all colours.

Adding a manual non tw style tag resolves it, e.g.: style={{ color: '#d7e5c7' }}

Sample code:

```typescript

        <Button
          href="https://dypt.app/tasks"
          className="mt-8 rounded-md bg-blue-600 px-3 py-2 text-sm text-gray-200"
        >
          Go to your tasks
        </Button>
```

It outputs like this, whereas the text should be gray:

image

The colour applied looks to be the typically "visited" url browser colour, but even using tailwinds visited: prefix classes doesn't override it.

**Comment by gabrielmfern** [comment]
> ```ts
>         <Button
>           href="https://dypt.app/tasks"
>           className="mt-8 rounded-md bg-blue-600 px-3 py-2 text-sm text-gray-200"
>         >
>           Go to your tasks
>         </Button>
> ```

Thanks for the feedback and for trying out the canary, you really helped finding the edge cases and rough edges here. This should be fixed on `@react-email/tailwind@0.0.13-canary.4`.

**Comment by tomschenkenberg** [comment]
I'm also testing the performance improvements with:
```
"@react-email/components": "^0.0.12-canary.0",
"@react-email/tailwind": "^0.0.13-canary.4",
"react-email": "1.9.5",
```
Am I testing this correct? 

I am seeing dramatic performance improvements, but lots of styles are not applied in the resulting email. I can provide the template+demo content if that helps.

**Comment by gabrielmfern** [comment]
> I'm also testing the performance improvements with:
> 
> ```
> "@react-email/components": "^0.0.12-canary.0",
> "@react-email/tailwind": "^0.0.13-canary.4",
> "react-email": "1.9.5",
> ```
> 
> Am I testing this correct?
> 
> I am seeing dramatic performance improvements, but lots of styles are not applied in the resulting email. I can provide the template+demo content if that helps.

If you could, it would be awesome.

**Comment by gabrielmfern** [comment]
> I've just published a debug repo: https://github.com/tomschenkenberg/react-email-debug
> 
> With pre-canary screenshot of the email and a post-canary screenshot, using `email dev`
> 
> Hope this helps!

I cloned your repo and tried using the `react-email/tailwind@0.0.13-canary.4` and the emails rendered just like in the pre-canary screenshot. The problem doesn't seem to be that you are importing from the wrong module so investigate your setup in depth a bit more, might be some sneaky detail that causes the emails to be rendered that way.

**Comment by gabrielmfern** [comment]
> Me again, afraid I found another issue.
> 
> Canary 4 now works perfectly locally, but deploying on vercel errors out. Reverting to an older version of react-email/tailwind resolves this (I tried 0.0.8).
> 
> I get this error in the vercel logs when I call this route (that triggers sending an email):
> 
> ```
> Error: Cannot find module 'postcss'
> Require stack:
> - /var/task/.next/server/chunks/934.js
> - /var/task/.next/server/webpack-runtime.js
> - /var/task/.next/server/app/api/cron/weekly-summary/route.js
> - /var/task/node_modules/.pnpm/next@14.0.4-canary.25_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/server.runtime.prod.js
> - /var/task/___next_launcher.cjs
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
>     at /var/task/node_modules/.pnpm/next@14.0.4-canary.25_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:11:25643
>     at Module._load (node:internal/modules/cjs/loader:901:27)
>     at r.<computed>.e._load (/var/task/___vc/__launcher/__launcher.js:14:2516)
>     at Module.require (node:internal/modules/cjs/loader:1115:19)
>     at w.require (/var/task/node_modules/.pnpm/next@14.0.4-canary.25_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:11:25859)
>     at require (node:internal/modules/helpers:130:18)
>     at ../../node_modules/.pnpm/tailwindcss@3.3.2_patch_hash=2ecqyyb3nnd4sclcv6omjvweii/node_modules/tailwindcss/lib/lib/setupContextUtils.js (/var/task/.next/server/chunks/934.js:44:227276)
>     at /var/task/.next/server/chunks/934.js:44:9293
>     at ../../node_modules/.pnpm/tailwindcss@3.3.2_patch_hash=2ecqyyb3nnd4sclcv6omjvweii/node_modules/tailwindcss/lib/lib/setupTrackingContext.js (/var/task/.next/server/chunks/934.js:2168:21036) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/var/task/.next/server/chunks/934.js',
>     '/var/task/.next/server/webpack-runtime.js',
>     '/var/task/.next/server/app/api/cron/weekly-summary/route.js',
>     '/var/task/node_modules/.pnpm/next@14.0.4-canary.25_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/server.runtime.prod.js',
>     '/var/task/___next_launcher.cjs'
>   ],
>   page: '/api/cron/weekly-summary'
> }
> ```

Can you try out `@react-email/tailwind@0.0.13-dev.user-build-problems.0` and see if things work well with it?

**Comment by Xexr** [comment]
That's done the trick 🙂

Seemed like an ESM problem - what was the issue?

**Comment by gabrielmfern** [comment]
> That's done the trick 🙂
> 
> Seemed like an ESM problem - what was the issue?

Great to hear! Honestly I'm not exactly sure what the issue was here 😅, but fixing a problem with vite fixed this as well because I changed our build process for the package

**Comment by tomschenkenberg** [comment]
> > I've just published a debug repo: https://github.com/tomschenkenberg/react-email-debug
> > With pre-canary screenshot of the email and a post-canary screenshot, using `email dev`
> > Hope this helps!
> 
> I cloned your repo and tried using the `react-email/tailwind@0.0.13-canary.4` and the emails rendered just like in the pre-canary screenshot. The problem doesn't seem to be that you are importing from the wrong module so investigate your setup in depth a bit more, might be some sneaky detail that causes the emails to be rendered that way.

Thanks Gabriel for your help, much appreciated! Just to be sure, these were my steps to reproduce the problem:

1. `npm run preview-email` (which executes `email dev --dir=src/emails`)
2. render the 'content-update' template, and looks OK on screen
3. use the 'Send' feature to email myself: now looks like the post-canary screenshot in Gmail

The same works fine pre-canary, but takes 7 seconds to render.

**Comment by gabrielmfern** [comment]
> > > I've just published a debug repo: https://github.com/tomschenkenberg/react-email-debug
> > > With pre-canary screenshot of the email and a post-canary screenshot, using `email dev`
> > > Hope this helps!
> > 
> > 
> > I cloned your repo and tried using the `react-email/tailwind@0.0.13-canary.4` and the emails rendered just like in the pre-canary screenshot. The problem doesn't seem to be that you are importing from the wrong module so investigate your setup in depth a bit more, might be some sneaky detail that causes the emails to be rendered that way.
> 
> Thanks Gabriel for your help, much appreciated! Just to be sure, these were my steps to reproduce the problem:
> 
>     1. `npm run preview-email` (which executes `email dev --dir=src/emails`)
> 
>     2. render the 'content-update' template, and looks OK on screen
> 
>     3. use the 'Send' feature to email myself: now looks like the post-canary screenshot in Gmail
> 
> 
> The same works fine pre-canary, but takes 7 seconds to render.

Oh, I didn't try sending it to myself. 

But still, seems like evenn sending it to gmail it looks fine still.
image

**Comment by tomschenkenberg** [comment]
> > Thanks Gabriel for your help, much appreciated! Just to be sure, these were my steps to reproduce the problem:
> > ```
> > 1. `npm run preview-email` (which executes `email dev --dir=src/emails`)
> > 
> > 2. render the 'content-update' template, and looks OK on screen
> > 
> > 3. use the 'Send' feature to email myself: now looks like the post-canary screenshot in Gmail
> > ```
> > The same works fine pre-canary, but takes 7 seconds to render.
> 
> Oh, I didn't try sending it to myself.
> 
> But still, seems like evenn sending it to gmail it looks fine still. 

OK, that's promising! It must be me. I've just added a Docker config to the repo, to rule out my local setup. But still get the post-canary layout in the (Google Workspace and normal) Gmail email. But outlook.com/live.com looks good however. 

I'll dig deeper into this.

**Comment by Xexr** [comment]
Ah I'm back again... sorry!

I was previously checking the gmail web app (as well as apple mail, outlook and protonmail). 

All of those are good, but the official gmail app (on iOS) is still borked. 

I wonder if this is related to Tom's issue above and we've been talking cross purposes with respect to 'gmail'. 

Here's what my email actually looks like in the gmail app:

image

**Comment by gabrielmfern** [comment]
> Ah I'm back again... sorry!
> 
> I was previously checking the gmail web app (as well as apple mail, outlook and protonmail).
> 
> All of those are good, but the official gmail app (on iOS) is still borked.
> 
> I wonder if this is related to Tom's issue above and we've been talking cross purposes with respect to 'gmail'.
> 
> Here's what my email actually looks like in the gmail app:
> 
> image

Hey thanks for testing that out! That might just be the reason the problem still happens, 

I'll tell you guys what, we really want to get these performance improvements into the hands of everybody and since this seems to be a relatively small compatibility issue I'll try fixing that on another minor release, thank you all for the feedback and patience with us on developing this, will get back to you guys soon.

**Comment by gabrielmfern** [comment]
> Ah I'm back again... sorry!
> 
> I was previously checking the gmail web app (as well as apple mail, outlook and protonmail).
> 
> All of those are good, but the official gmail app (on iOS) is still borked.
> 
> I wonder if this is related to Tom's issue above and we've been talking cross purposes with respect to 'gmail'.
> 
> Here's what my email actually looks like in the gmail app:
> 
> image

@Xexr, Is this issue the same as from this comment https://github.com/resend/react-email/issues/1095#issuecomment-1865394227 or no?

**Comment by Xexr** [comment]
> > Ah I'm back again... sorry!
> 
> > 
> 
> > I was previously checking the gmail web app (as well as apple mail, outlook and protonmail).
> 
> > 
> 
> > All of those are good, but the official gmail app (on iOS) is still borked.
> 
> > 
> 
> > I wonder if this is related to Tom's issue above and we've been talking cross purposes with respect to 'gmail'.
> 
> > 
> 
> > Here's what my email actually looks like in the gmail app:
> 
> > 
> 
> > image
> 
> 
> 
> @Xexr, Is this issue the same as from this comment https://github.com/resend/react-email/issues/1095#issuecomment-1865394227 or no?

Afraid it appears to be different.

Assuming this was included in the v14 canary?

In the gmail app, it still looks like this:

image
